### ISSUE TITLE
Trigger of general change

### ISSUE THREAD

**Issue by torstengram** [Thorarin/com.sensative#11]
Hello, is it possible to add a trigger that is able to trigger a flow on a general status change of any sensative strip, no matter the value?

**Comment by Thorarin** [comment]
I would try creating a flow that triggers on one of Homey's built-in "Devices" cards, like "A sensor's value changed". You can then filter it down using Logic cards as needed.

For alarms you need to use "An alarm turned on" or "An alarm turned off" instead. So yeah, to get literally any change, you would still need three flows, I suppose.
