### ISSUE TITLE
Comfort temp alarm

### ISSUE THREAD

**Issue by cortinaman** [Thorarin/com.sensative#12]
Hi

Good job on adding support for the Drip/Comfort in the Beta version. I understand this is still work in progress, just wondering if I missed something or it's not implemented yet.

First, I notice there is a common device template for the Drip and Comfort. The settings template contains both the Leakage/Moisture settings and Temperature settings. This is fine, what's more confusing is that the HMI Faceplate displays data for both sensor types.

Secondly, I added a Comfort sensor close to the living room fireplace. This way I can detect when the fireplace is lit and turn off electric heating before the room temperature starts rising. Being battery powered it does not report continuously, but I believe the temperature alarms will trigger a wake-up and forced report. The problem is that there is no access to the temperature alarms in the flow editor, neither as trigger nor condition.

Am I doing something wrong or are these future features?

Kindly
Frode, Norway

**Comment by BugHoarder** [comment]
Drips and Comfort both use the same product ID, so it isn't really possible for the gateway to distinguish between the two. Drips and Comfort both support the same sensorics, however one is more suited for temperature measurement while the other for leakage detection.

A point about temperature alarms as well. The unit will send the current temperature value once a temperature alarm has been triggered, so if possible you can use that to trigger scenes etc.

**Comment by cortinaman** [comment]
Thank you. But I'm not sure I follow. I understand what you say about same product ID and how this affect setup, are you also saying the temperature alarms are not accessible to the app? I have one sensor of each type. I tried wetting the Drips and noticed the water alarm flashing in the HMI faceplace, but I'm not able to replicate this for the Comfort's heat alarm.

Yes, currently I use the temperature value and evaluate whether it's rising or falling to trigger actions. But it would expand the options and reduce logic complexity if temperature alarms where available in flows, 

Regarding the same product ID being used for both, would it be possible to make two versions with different data subsets? The user knows which model he is installing and would select the correct version, the procuct ID is not presented at the time of selecting device.

Regards,
Frode

**Comment by Thorarin** [comment]
It looks like the heat alarm capability is advertised, but probably the parsing of the event is missing.
I will have to check that. I think there were also some issues with setting parameters on the Comfort/Drip.

I'm not sure what adding two devices with the same ID will do. Perhaps it would work if you explicitly add a device, but you can also add Z-Wave devices without explicitly selecting it, in which case it would be impossible to automatically select the right one. Worst case the driver would not work at all of it would lead to undefined behavior.

I might do some experimentation, but I can't make any promises. The time I have for this project is limited and I mostly want to get the driver out of beta right now :smile:

**Comment by dparyani** [comment]
Hi!

As conveyed earlier,  the configuration parameter in the driver are old. There were new parameters introduced before summer and corresponding updates in your driver were uploaded here to be considered.

https://github.com/Thorarin/com.sensative/pull/5
