### ISSUE TITLE
Fix Correct Configuration Parameters for Strips Multi-Sensors Comfort and Drip

### ISSUE THREAD

**Issue by dparyani** [Thorarin/com.sensative#13]
Is it possible to update the Strips Multi-Sensor driver with the latest configuration parameters and respective settings, that has been released.

Please refer:
https://www.stripsbysensative.com/wp-content/uploads/2017/05/WEB.Strips_drip_textmanual_EU_GB_INS-11-02-011-2-P5.pdf

[Athom_Homey.zip](https://github.com/Thorarin/com.sensative/files/2515259/Athom_Homey.zip)

**Comment by Thorarin** [comment]
This should be fixed in #15, available as 2.0.1 beta release.
