### ISSUE TITLE
The beta version doesn't work with Homey V2

### ISSUE THREAD

**Issue by nanderss** [Thorarin/com.sensative#14]
I can't add the beta version to my Homey, and I'm running the latest Homey beta. I can't use the 1.* version of the app since that doesn't work with the Homey V2 beta. Probably because it requires apps to use V2 of the Homey API.

**Comment by mruiter** [comment]
All versions work on V2 and v1 if you refer to the door strip . Tested and running on multiple homeys 

Verstuurd vanaf mijn iPhone

**Comment by nanderss** [comment]
I have the Comfort strip with light and temperature sensor. I can't add it with 1.* of the app, and I can't add the beta for v2 of the app to my Homey.

**Comment by mruiter** [comment]
What is can not add ? If the app isn’t working it should add but as a generic devices . You should have a device card that does nothing . If it doesn’t add at all I guess there is something wrong with the strip , maybee wrong country so it’s on another frequency .

**Comment by nanderss** [comment]
I'm talking about adding the beta version of the Sensative app to my Homey. When I try to switch to the beta version I get this:

![img_1643](https://user-images.githubusercontent.com/1815977/50610145-2fd63800-0ed2-11e9-87a2-1c3613039449.png)

**Comment by kjettern** [comment]
+1 on the add issue.. You should update the app to be allowed to be installed on >2.0

**Comment by nanderss** [comment]
@kjettern So I was afraid that I wasn't clear enough on the issue, but I'm glad to see that I'm not the only one. As I understand it, and @mruiter, please correct me if I'm wrong, the issue basically is this line:

https://github.com/Thorarin/com.sensative/blob/10f3a76b064d0fbaabd37a30ba71c52145ce08d7/app.json#L22

**Comment by Thorarin** [comment]
Hmm, that warning about the beta channel must be new... I'll try to get the 2.0 version ready for final release this weekend, but I can't make any promises. As I recall, there were some issues with the settings for the Strips Comfort remaining to be fixed.

I'd rather not patch the old version of the app, but if I run into issues that may yet be an option.

**Comment by Thorarin** [comment]
@nanderss @mruiter I still found a number of problems with the previous 2.0.0 beta of the Sensative app, so I put out another beta version first (#15). New installations can be performed on Homey 2.0 now.

Feel free to try it, or have a little more patience if you don't want to have the hassle of switching back to stable.
