### ISSUE TITLE
Alarm wont reset

### ISSUE THREAD

**Issue by ostracus** [Thorarin/com.sensative#18]
Hi Firstly thx for developing the app, great work. I was wondering why I cannot reset an alarm. Both the heat alarm and water alarm went off as I connected the strips (I have 3 Comfort) and the keep the alarm state from first connection. I am using the strips with Homey. Any idea why?

**Comment by CaptainHolger** [comment]
Same issue for me. Also I added 2 Guard strips and both of them show Tamper alarm triggered with no option to disable. AFAIK guard strips do not even have tamper alarm function.

**Comment by ricott** [comment]
Same here, my strip drip shows a heat alarm that wont go away. Also default setting is "Temperature alarms=No" - which I would guess means no temp alarm should be triggered.

**Comment by ppagard** [comment]
Hi, 
Thank you for developing this app!
I have the same issue as above on one of my Homey's (have two).
And on the homey that still works as expected I run version 2.0.1 (beta) with one Strips Drip!
And on the homey that has this issue I run version 2.0.1. with three Strips Drip and one Strips Guard!
The Strips Guard works perfectly, but all my Strips Drip has both heat and water alarm always active.

I hope this can be helpful for you!

Best regards.

**Comment by TheoBlub** [comment]
Hi, 
Encountered the same problem today. Reset the Strip and rejoined the Strip again but still (again) have a leakage-alarm. Changed also the alarm settings and submitted the changes successfully. That doesn't help. 

Thank for providing the app by the way!

Theo

**Comment by thomasAFK** [comment]
Hi and thank you for developing! I have the same issue. My strips comfort have both heat alarm and water alarm always on, no way to turn off (tried turning off temperature reporting, temperature alarms etc). This started after my first reset of the strip. My strips Drip have heat alarm always on since first reset.

**Comment by efurdal** [comment]
Tamper alarm godt stuck on Guard and Water alarm got stuck on Drip.
I had to remove the sensors and add them again. Seems like they perform well now. Have't tested the tamper alarm, but the water alarm goes off when there is no water.

**Comment by pelti51** [comment]
I have the same issue with drips. Temperature and leak alarm are always on and don't come off. The resetting or re-pairing don't help.

**Comment by follox** [comment]
I got the drip\comfort edition and my heat and water alarm is always on. Does not help to re-include.

**Comment by Thorarin** [comment]
I think we're talking about two different problems here. The tamper alarm I've experienced myself before, but I don't have a working solution yet.

As for the drip/comfort alarms, I haven't been able to reproduce that issue yet. I'll try to investigate, but I cannot make any promises on when that will be, I'm afraid.

**Comment by anaxyd** [comment]
I have a fix ready for review #21

**Comment by Thorarin** [comment]
I sometimes experience the same issue when re-adding my Strips Comfort. I'm not quite sure why it happens, but I've added maintenance actions to reset the alarms if necessary.

This is a relatively new Homey feature (3.1), so it wasn't possible to do something like this before. Well, not in a clean way at least 🙂
