### ISSUE TITLE
Tamper alarm keeps blinking

### ISSUE THREAD

**Issue by LesPaul1962** [Thorarin/com.sensative#20]
On the website of the manufacturer it says this is the problem:  A tamper alarm is an event and should be reset by your gateway UI.

**Comment by anaxyd** [comment]
I have a fix ready for review #21

**Comment by Thorarin** [comment]
@anaxyd Sorry, I didn't get around to it last weekend. I didn't get my development PC back up and running until late Sunday. I'll try to do it soon™

**Comment by Thorarin** [comment]
Version 2.1.0 adds a maintenance action to reset the tamper alarm after it has been triggered.

This is a relatively new Homey feature (3.1), so it wasn't possible to do something like this before. Well, not in a clean way at least 🙂
