### ISSUE TITLE
Tamper-Alarm at sensors without any reason

### ISSUE THREAD

**Issue by dirkg173** [Thorarin/com.sensative#29]
Hello @Thorarin 
since Athom released the Homey firmware version 5.0 Beta, tamper alarms have been activated on various Z-Wave sensors from different manufacturers (in mine case Fibaro, Aeotec, POPP, Sensative) for no reason. If you deactivate the tamper alarms by waking up the sensor, the tamper alarm will activate within the next few hours up to 2-3 days without any reason.
Athom seems to have solved this problem with their Fibaro App. Since 9 days the tamper alarm has not been activated on door/window sensors, motion sensors and water sensors.
However, the problem still occurs on my Comfort Strip from Sensative.
I have 6 pieces of Guard Strips in use, on which the tamper problem has not yet occurred.

For this reason I kindly ask you to contact Athom or Marco Ruiter (because he is listed as a co-worker and knows about the problem) regarding the problem with the tamper alarms and fix the error in the Sensative app.

Thank you in advance!

Kind regards,
Dirk

**Comment by Thorarin** [comment]
Don't deactivate the tamper alarm by waking up the Strips.
Use the maintenance actions instead and there shouldn't be an issue.

**Comment by dirkg173** [comment]
Sorry, this was a copy / paste text.
Of course I used the maintenance action, but the tamper alarm is activated again without reason.

**Comment by Thorarin** [comment]
Hmm, peculiar.. I've been using 5.0 release candidates for a long time now, but I haven't experienced this issue at all myself.
I can try removing the getOnOnline setting from alarm_tamper, but it's strange that different people appear to get different behavior out of what should be the same devices.

**Comment by dirkg173** [comment]
Please contact Marco Ruiter. He seems to know exactly what the problem is. It seems that the problem is also caused by Homey FW and not by Sensitive App.

https://github.com/mruiter/com.popp/issues/80#issuecomment-716135072

**Comment by mruiter** [comment]
Yes you need to remove all getonline requests on all battery powered devices . Also update to the latest mesh driver 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
﻿Yes you need to remove all getonline requests on all battery powered devices . Also update to the latest mesh driver 

Verstuurd vanaf mijn iPhone

**Comment by Thorarin** [comment]
I didn't need to contact him, because I already knew about the changes in Homey 5.0 😋 In fact, I was one of the people that reported the issue that got fixed. Unfortunately Athom managed to break something else, which is the real issue.

Anyway, you can try using https://homey.app/nl-nl/app/com.sensative/Sensative/test/ (2.2.1 test version) to see if that fixes the issue.

**Comment by dirkg173** [comment]
Thank you very much. I have installed the test version and will observe whether the tamper alarms appear again.

**Comment by dirkg173** [comment]
Hi Marcel,
after round 14 days the heat and water alarm was activated again with no reason.
At the screenshot you can see the on and offs of the last couple weeks.
In every case there was no reason to activate any alarm.

Info: As I updated your app 9 days ago I didn’t restart the app or used the maintenance action, because there was no alarm activated.

![A5C9610A-3B4D-40F0-A1FF-2EDE916D1E1F](https://user-images.githubusercontent.com/40319629/97974609-1f41c200-1dc8-11eb-91e6-3237e9ec8148.jpeg)

**Comment by Thorarin** [comment]
I didn't know this issue also occurred for you for the other alarms; the original issue only mentioned the tamper alarm.
I'll try to release another test version soon.

It would have been nice if Athom would have actually implemented the Z-Wave protocol properly for a change, instead of creating new issues 😞

**Comment by mruiter** [comment]
It occurs on all notification alarm classes on battery devices . So the online parameter needs to be removed on all notifications.
If that’s already the case the problem isn’t solved yet

I also had a user report another false alarm on a neo pir and those have all getonline statuses removed 

Verstuurd vanaf mijn iPhone

**Comment by Thorarin** [comment]
@mruiter I overlooked some getOnOnline option, so it's not really a surprise that this is happening.
I'm just annoyed that Athom cannot get this part of the protocol right 😛 Their explanation about the frames being interpretable in multiple ways is just nonsense.

**Comment by mruiter** [comment]
They have a lot of things in zwave that’s not right . Security is a complete mess that’s why everybody is forcing them to include unsecure . S2 security is completely laggy and FLIRS isn’t implemented so the newer battery powered low power devices only work onder every 10 times you send a command to it ..

I completely agree . Zwave is a mess . Zigbee seems to be a bit better atm now that the rewrite is done . I hope the will do a third zwave rewrite after that 😂

Verstuurd vanaf mijn iPhone

**Comment by dirkg173** [comment]
Can you programmers unite and put pressure on Athom?
If I report bugs as a simple user, Athom sometimes doesn't take me seriously and sometimes they play for time. I do encourage other users to contact Athom, but I don't know if it really helps.

**Comment by Thorarin** [comment]
@dirkg173 Honestly, I'm a bit out of touch with the low level details of Z-Wave at the moment, since Athom is supposed to hide those details from us 😃 I might raise an issue if I gain more insight on what is happening and what can be done about it.

In the meantime, we can only do what Athom suggests and get rid of proactively getting sensor values when a device wakes up. It should fix your immediate issue.

**Comment by mruiter** [comment]
Haha there is 0.00000000000000000001% effect if one puts pressure on athom .

They have there own opinion on how zwave should be . And are not following / support the standard 

Verstuurd vanaf mijn iPhone

**Comment by dirkg173** [comment]
@Thorarin, ok, understand. But Athom has also published several codes on GitHub. However, I'm not a programmer, so I don't know if these codes could help.

@mruiter, not one programmer, many programmers. Without you private programmers, Athom would be nothing, 0, zero...

**Comment by mruiter** [comment]
We tried .. many times ... they just go silent 

Verstuurd vanaf mijn iPhone

**Comment by dirkg173** [comment]
What a pity, very sad...

**Comment by Thorarin** [comment]
I've published version 2.2.2 to test. That should hopefully get rid of your other alarms, as well as the tamper alarm.

**Comment by dirkg173** [comment]
Okay, thanks. I have installed the testversion and will check the behaviour and give you a feedback.

**Comment by dirkg173** [comment]
Sorry for really late reply. I forgot to inform you, sorry.
Since v2.2.2 I had no tamper-alarm. So for me the bug is fixed.
Thank you very much @Thorarin!
