### ISSUE TITLE
faulty insights

### ISSUE THREAD

**Issue by satbopper** [Thorarin/com.sensative#3]
to be short,the strip is working fine,but if the strip is in rest,so the device is not showing alarm
the insights is showing alarm.
i had this also with the homey firmware 1.0.3 and now 1.0.4 also,with the latest strips 1.0.3

**Comment by mruiter** [comment]
i see this on all binary sensors, door motion etc . looks like an insights error

Verstuurd vanaf mijn iPad

**Comment by Thorarin** [comment]
What Marco said :) Insights on binary sensors seem te be inverted at the moment.
