### ISSUE TITLE
Strange behavior of the battery charge level

### ISSUE THREAD

**Issue by dirkg173** [Thorarin/com.sensative#34]
Has anyone ever noticed similar behavior?

<img width="859" alt="Bildschirmfoto 2021-06-21 um 11 38 17" src="https://user-images.githubusercontent.com/40319629/122745982-d9b80380-d289-11eb-98e4-4d975f02bab9.png">

Why does the battery charge level drops directly from 75% to 25% and not to 50%?

I know that in general the battery information in Homey is very unreliable, so the question is whether it is a problem of Homey or of the Sensative App.
Should I report the problem also to Athom?

**Comment by Thorarin** [comment]
I've not reached 25% on any Strips yet myself, but this behavior doesn't surprise me at all. I see the same happenon other battery sensors from different brands. In fact, just the other day a sensor stopped working with the last reported battery still at 77%.

As far as I know, it basically has to do with how good batteries have become. These battery indicators are typically based on output voltage, but modern batteries hardly show a drop in voltage until they are almost empty.

If you want more details, I would suggest reaching out to Sensative directly. I doubt this behavior has anything to do with Homey specifically.
