### ISSUE TITLE
Hello Thorarin

### ISSUE THREAD

**Issue by mruiter** [Thorarin/com.sensative#4]
Are you still activly using homey ? And maintaning the sensative strip app ?

If not , i would like to upgrade the app to the new sdkv2 version and add the support for the other models of the strip

**Comment by Thorarin** [comment]
Yep, still using it.

There hasn't been a lot of maintenance necessary to be honest. There is one issue in combination with an old Strips firmware that I haven't been able to solve yet.

As for the new SDK version, I planned to upgrade to it somewhere in December when I have some time off from work.

I wasn't aware that any new products had been added to the Strips family. It looks like the products are not actually generally available yet though. Of course, we can try to add support from the specs sheets, but I'm not sure how reliable that will be.

**Comment by mruiter** [comment]
I'm almost finished with the SDKv2 rewrite. was in a conference call again :)
Just a new picture , ill push it to you git as soon as i have the time 2 test.
