### ISSUE TITLE
Strip Comfort (temp/lux meter) not working/can't add it

### ISSUE THREAD

**Issue by Hellosmarthome** [Thorarin/com.sensative#7]
Can you please make support for this device?

See the XML for the device description. If you need help testing please let me know.

Thank you!

**Comment by Thorarin** [comment]
I'm working on it. I'm hoping to get around to it this weekend, but it may take longer.

I won't be able to test though, as I don't own one and have no need for one.

**Comment by Hellosmarthome** [comment]
Ok, great! Thank you.

I own one ...so if i can help let me know. Can you send me your e-amailaddress in this form please: https://www.domotica-blog.nl/contact

**Comment by Thorarin** [comment]
@DomoticaBlog I've published a beta version of the app, which should add support for Strips Drip and Strips Comfort. As I mentioned, I haven't been able to test it myself, so YMMV.

**Comment by Hellosmarthome** [comment]
Going to have a look.

Thank you!

**Comment by Hellosmarthome** [comment]
Looks like it's working. But i have to do some more testing because i think the lux is not updating.

But good job sofar!

One other thing. Can you change the description when u add the device. Because it's different then the guard.  Have a look in the manual here: https://www.stripsbysensative.com/wp-content/uploads/2017/05/WEB.Strips_comfort_textmanual_EU_GB_INS-11-02-011-1-R6.pdf

**Comment by Hellosmarthome** [comment]
Did some more testing.

It's working! Thanks again.

**Comment by Thorarin** [comment]
@DomoticaBlog Are you talking about the instructions for waking up the device? From the manual you linked, the method seems to be exactly the same as the Strips Guard? I'm not sure what difference you're getting at.

Thanks for testing 😃 

PS: looking at the current code, I have some doubts if setting any of the device parameters will actually work. Did you test that?
